#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');

$loader = new EngineCore\ConfigurationLoader(
    __DIR__ . '/console/config/_all.php',
    [
        'yii'              => __DIR__ . '/vendor/yiisoft/yii2/Yii.php',
        'common/bootstrap' => __DIR__ . '/common/config/bootstrap.php',
        'app/bootstrap'    => __DIR__ . '/console/config/bootstrap.php',
    ],
    [
        'extensions/config' => __DIR__ . '/extensions/config.php',
        'common/main'       => __DIR__ . '/common/config/main.php',
        'common/db-local'   => __DIR__ . '/common/config/db-local.php',
        'common/extension'  => __DIR__ . '/common/config/extension.php',
        'common/main-local' => __DIR__ . '/common/config/main-local.php',
        'app/main'          => __DIR__ . '/console/config/main.php',
        'app/extension'     => __DIR__ . '/console/config/extension.php',
        'app/main-local'    => __DIR__ . '/console/config/main-local.php',
    ],
    [
        'common/params'       => __DIR__ . '/common/config/params.php',
        'common/params-local' => __DIR__ . '/common/config/params-local.php',
        'app/params'          => __DIR__ . '/console/config/params.php',
        'app/params-local'    => __DIR__ . '/console/config/params-local.php',
    ]
);

$exitCode = (new yii\console\Application($loader->getConfig()))->run();
exit($exitCode);